# typed: false
# frozen_string_literal: true

# This file was generated by GitHub Actions. DO NOT EDIT.
class Ghdesk < Formula
  desc "Fullscreen GitHub TUI for your PRs and issues with preview support"
  homepage "https://github.com/inamuu/ghdesk"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/inamuu/ghdesk/releases/download/v0.1.0/ghdesk_0.1.0_darwin_amd64.tar.gz"
      sha256 "117f0f96ca9fb777d98e58343c6762c4a83a48508ee6d01826356d2262b11c13"

      def install
        bin.install "ghdesk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/inamuu/ghdesk/releases/download/v0.1.0/ghdesk_0.1.0_darwin_arm64.tar.gz"
      sha256 "3c19c8e9f1a332d7c563f58e54ae9e39c95dd6de3e335ada2807fe3297c165ee"

      def install
        bin.install "ghdesk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/inamuu/ghdesk/releases/download/v0.1.0/ghdesk_0.1.0_linux_amd64.tar.gz"
      sha256 "230a9fde2f18a35aadf2adae2efd62f8de0f84ff3447bdecd5380a3f350f294e"

      def install
        bin.install "ghdesk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/inamuu/ghdesk/releases/download/v0.1.0/ghdesk_0.1.0_linux_arm64.tar.gz"
      sha256 "79e7d3113f05f28f0dff89293010a4216800343402f2338a6b5a4434c82b5afc"

      def install
        bin.install "ghdesk"
      end
    end
  end

  test do
    system "#{bin}/ghdesk", "--version"
  end
end
