# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Overix < Formula
  desc "YAML-based lightweight configuration management CLI"
  homepage "https://github.com/inamuu/overix"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/inamuu/overix/releases/download/v0.1.3/overix_0.1.3_darwin_amd64.tar.gz"
      sha256 "043e1881cb85a0f9d8b6c6b171abdab6d7ca57aad19725a7e34ff3ff42990935"

      define_method(:install) do
        bin.install "overix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/inamuu/overix/releases/download/v0.1.3/overix_0.1.3_darwin_arm64.tar.gz"
      sha256 "779b4f8e389b2fa534f5261cf33d9739c801e8a246ca721043c703b01e210f46"

      define_method(:install) do
        bin.install "overix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/inamuu/overix/releases/download/v0.1.3/overix_0.1.3_linux_amd64.tar.gz"
      sha256 "8e5edd2eea8691827e2b7642223aebdc89b5995a0f1abe4ec7a90cf9f749e971"
      define_method(:install) do
        bin.install "overix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/inamuu/overix/releases/download/v0.1.3/overix_0.1.3_linux_arm64.tar.gz"
      sha256 "1fb544398731c5ca2cd4e425346b2fb49fcd1a0b8876549283de2ab35a75662e"
      define_method(:install) do
        bin.install "overix"
      end
    end
  end

  test do
    system "#{bin}/overix", "version"
  end
end
