# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SsmLocalScript < Formula
  desc "Run commands or local scripts on SSM-managed EC2 instances"
  homepage "https://github.com/inamuu/ssm-local-script"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/inamuu/ssm-local-script/releases/download/v0.1.0/ssm-local-script_0.1.0_darwin_amd64.tar.gz"
      sha256 "0e1af0e2a1e9ca8e29a7df7947341245782e5b31ff3a5d3ca7105b91945575c3"

      define_method(:install) do
        bin.install "ssm-local-script"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/inamuu/ssm-local-script/releases/download/v0.1.0/ssm-local-script_0.1.0_darwin_arm64.tar.gz"
      sha256 "a6dbd76e0aa769b2630511f20188205ca00f131e41b453e4dfc37c8142059ab0"

      define_method(:install) do
        bin.install "ssm-local-script"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/inamuu/ssm-local-script/releases/download/v0.1.0/ssm-local-script_0.1.0_linux_amd64.tar.gz"
      sha256 "1fde4d62f5d6eaaa92fe7c8a1562c6ff8fbdc6b691425896b09d86f7435d8738"
      define_method(:install) do
        bin.install "ssm-local-script"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/inamuu/ssm-local-script/releases/download/v0.1.0/ssm-local-script_0.1.0_linux_arm64.tar.gz"
      sha256 "ce3956fdb02cc71e94ef47cca60c299cdbc7d614a8b903aeca50014254b044fd"
      define_method(:install) do
        bin.install "ssm-local-script"
      end
    end
  end

  test do
    output = shell_output("#{bin}/ssm-local-script 2>&1", 1)
    assert_match "Usage:", output
  end
end
