# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ssmx < Formula
  desc "AWS SSM Session Manager CLI with configurable keepalive"
  homepage "https://github.com/inamuu/ssmx"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/inamuu/ssmx/releases/download/v0.1.3/ssmx_0.1.3_darwin_amd64.tar.gz"
      sha256 "867f86e3956cee3302befb2017fb5f3e6df5ddcc98b53081b14049adee45fbb1"

      define_method(:install) do
        bin.install "ssmx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/inamuu/ssmx/releases/download/v0.1.3/ssmx_0.1.3_darwin_arm64.tar.gz"
      sha256 "e4714a3ec989506cbb113a33e70748cb202a0ca2cf84627bcf71cdb84ca84e1d"

      define_method(:install) do
        bin.install "ssmx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/inamuu/ssmx/releases/download/v0.1.3/ssmx_0.1.3_linux_amd64.tar.gz"
      sha256 "dd106b8924ba1b8a253ce47f059575f762b0000d2985227451bc1963d3f89adb"
      define_method(:install) do
        bin.install "ssmx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/inamuu/ssmx/releases/download/v0.1.3/ssmx_0.1.3_linux_arm64.tar.gz"
      sha256 "53fff77d2396d2bfa488bd60376fd58cf36500397c23f4d480f7ebe56a47fb32"
      define_method(:install) do
        bin.install "ssmx"
      end
    end
  end
end
