# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ssmx < Formula
  desc "AWS SSM Session Manager CLI with configurable keepalive"
  homepage "https://github.com/inamuu/ssmx"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/inamuu/ssmx/releases/download/v0.1.6/ssmx_0.1.6_darwin_amd64.tar.gz"
      sha256 "368b1a9eb150c2e41e978c7795a97a8664261fc56eaaa649f7b94fa3835d126d"

      define_method(:install) do
        bin.install "ssmx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/inamuu/ssmx/releases/download/v0.1.6/ssmx_0.1.6_darwin_arm64.tar.gz"
      sha256 "12785693f4dd2f461562eed0cdf3e01e2660214a6af80b5dd1f6a370e178ad85"

      define_method(:install) do
        bin.install "ssmx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/inamuu/ssmx/releases/download/v0.1.6/ssmx_0.1.6_linux_amd64.tar.gz"
      sha256 "e02da2c844053cd65a9f120f764a7a37bcc5a5790be8cba5fd901c043107bff0"
      define_method(:install) do
        bin.install "ssmx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/inamuu/ssmx/releases/download/v0.1.6/ssmx_0.1.6_linux_arm64.tar.gz"
      sha256 "e57a166c1196ac163a17fbb6eff25fd24ac62b7f9942be26b7d7771fd93cf1e2"
      define_method(:install) do
        bin.install "ssmx"
      end
    end
  end
end
