# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfz < Formula
  desc "A small, fast TUI for running Terraform plan/apply with optional targets."
  homepage "https://github.com/inamuu/tfz"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/inamuu/tfz/releases/download/v0.1.8/tfz_0.1.8_darwin_amd64.tar.gz"
      sha256 "46296ca82b9c47e0b9af30683cd8de91909a3f0f908f1e54d28af60b6653344f"

      def install
        bin.install "tfz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/inamuu/tfz/releases/download/v0.1.8/tfz_0.1.8_darwin_arm64.tar.gz"
      sha256 "5da0724b1533d1463752d4d64582210fde3a1e8669cab4f5257fe7dffdf06cad"

      def install
        bin.install "tfz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/inamuu/tfz/releases/download/v0.1.8/tfz_0.1.8_linux_amd64.tar.gz"
      sha256 "855f84e1da7c59ec642de82980ec2955cf7c0f7cfbac5813a6b06d3130269c89"
      def install
        bin.install "tfz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/inamuu/tfz/releases/download/v0.1.8/tfz_0.1.8_linux_arm64.tar.gz"
      sha256 "8f71b5f0d8517d15e2d9e66cd4cc0a58c7d4e25915915256d39899c421ed30f2"
      def install
        bin.install "tfz"
      end
    end
  end

  def caveats
    <<~EOS
      `tfz` needs Terraform in your PATH.
    EOS
  end

  test do
    system "#{bin}/tfz", "--version"
  end
end
