# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfz < Formula
  desc "A small, fast TUI for running Terraform plan/apply with optional targets."
  homepage "https://github.com/inamuu/tfz"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/inamuu/tfz/releases/download/v0.1.7/tfz_0.1.7_darwin_amd64.tar.gz"
      sha256 "460f398f3033e1ce624b495438392ea269d11a36f521dd514274e03465991fa8"

      def install
        bin.install "tfz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/inamuu/tfz/releases/download/v0.1.7/tfz_0.1.7_darwin_arm64.tar.gz"
      sha256 "a1c727c1e3d6cf3acf56b97e03a5e0fd2c90a99f8ccf771545f8effb86b76a03"

      def install
        bin.install "tfz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/inamuu/tfz/releases/download/v0.1.7/tfz_0.1.7_linux_amd64.tar.gz"
      sha256 "c64334a5f908eb1dbdab81bed3defdc5c5d044826e143dc16cce77bb105e41a2"
      def install
        bin.install "tfz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/inamuu/tfz/releases/download/v0.1.7/tfz_0.1.7_linux_arm64.tar.gz"
      sha256 "ec64af863dd60c9846fa32aa75dbea1598295a632e1152ec43f23fa6e0dd2e19"
      def install
        bin.install "tfz"
      end
    end
  end

  def caveats
    <<~EOS
      `tfz` needs Terraform in your PATH.
    EOS
  end

  test do
    system "#{bin}/tfz", "--version"
  end
end
