# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfz < Formula
  desc "A small, fast TUI for running Terraform plan/apply with optional targets."
  homepage "https://github.com/inamuu/tfz"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/inamuu/tfz/releases/download/v0.1.5/tfz_0.1.5_darwin_amd64.tar.gz"
      sha256 "520e90576b44f173cb90ab50be8cd9283c0e22e0b04611cbfc32b222ae0f96ae"

      def install
        bin.install "tfz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/inamuu/tfz/releases/download/v0.1.5/tfz_0.1.5_darwin_arm64.tar.gz"
      sha256 "2ff64a7bcd6d81830a13152f8ac8c9a50ac8e219883c7dd8cbbab4313a704f42"

      def install
        bin.install "tfz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/inamuu/tfz/releases/download/v0.1.5/tfz_0.1.5_linux_amd64.tar.gz"
      sha256 "498a741240f64c6a182c7869caa06301e60a2bee2abd9ffa27b7a41d4c5b5827"
      def install
        bin.install "tfz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/inamuu/tfz/releases/download/v0.1.5/tfz_0.1.5_linux_arm64.tar.gz"
      sha256 "3e180249325c69457f465250c4449f6b3e6ab915f3f538cab450d652ddebe576"
      def install
        bin.install "tfz"
      end
    end
  end

  def caveats
    <<~EOS
      `tfz` needs Terraform in your PATH.
    EOS
  end

  test do
    system "#{bin}/tfz", "--version"
  end
end
