# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vigilo < Formula
  desc "Watch command output and notify on pattern matches or exits."
  homepage "https://github.com/inamuu/vigilo"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/inamuu/vigilo/releases/download/v0.2.0/vigilo_0.2.0_darwin_amd64.tar.gz"
      sha256 "9b8001eb2e5cbff1f024ee2b122eefc2ddafc1f816ecdfbf775daab98b55a3d0"

      def install
        bin.install "vigilo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/inamuu/vigilo/releases/download/v0.2.0/vigilo_0.2.0_darwin_arm64.tar.gz"
      sha256 "d40a0ecfa57ce51d4d502f7efa7e1ddd77f46c7ef6068791dfe37e3faad7b6f0"

      def install
        bin.install "vigilo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/inamuu/vigilo/releases/download/v0.2.0/vigilo_0.2.0_linux_amd64.tar.gz"
      sha256 "6fb6b3e2375dfa6891c7771d6bfc3304ee0f1da62a7122bfee00e552d6dd2488"
      def install
        bin.install "vigilo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/inamuu/vigilo/releases/download/v0.2.0/vigilo_0.2.0_linux_arm64.tar.gz"
      sha256 "211c29696ce8045c51e3acca6fd1ac026f975929aa530c2a8fcd6b1113a1949f"
      def install
        bin.install "vigilo"
      end
    end
  end

  def caveats
    <<~EOS
      `vigilo --notify osascript` requires macOS.
      `vigilo --notify slack` requires `~/.config/vigilo/config.yaml`.
    EOS
  end

  test do
    system "#{bin}/vigilo", "--version"
  end
end
